
from PyQt5.QtGui import QFont

FONT1 = QFont()
FONT1.setPointSize(8)
FONT1.setBold(True)
FONT1.setFamily("Arial")

FONT8 = QFont()
FONT8.setPointSize(8)
FONT8.setBold(True)
FONT8.setFamily("Arial")

FONT10 = QFont()
FONT10.setPointSize(8)
FONT10.setBold(True)
FONT10.setFamily("Arial")

FONT11 = QFont()
FONT11.setPointSize(11)
FONT11.setBold(True)
FONT11.setFamily("Arial")

TABLE_HEADER_FONT = QFont()
TABLE_HEADER_FONT.setPointSize(10)
TABLE_HEADER_FONT.setBold(True)
TABLE_HEADER_FONT.setFamily("Arial")

TABLE_FONT = QFont()
TABLE_FONT.setPointSize(9)
TABLE_FONT.setBold(True)
TABLE_FONT.setFamily("Arial")

SUMMARY_GBOX_TITLE = QFont()
SUMMARY_GBOX_TITLE.setPointSize(11)
SUMMARY_GBOX_TITLE.setBold(True)
SUMMARY_GBOX_TITLE.setFamily("Arial")

SUMMARY_RECPT_TITLE_COLOR='QGroupBox:title {color: green;}'
SUMMARY_PAYMT_TITLE_COLOR='QGroupBox:title {color: red;}'
SUMMARY_CASHBALANCE_TITLE_COLOR='QGroupBox:title {color: blue;}'

RECEIPT_SUMMARY_LABEL_FONT=QFont()
RECEIPT_SUMMARY_LABEL_FONT.setPointSize(10)
RECEIPT_SUMMARY_LABEL_FONT.setBold(True)
RECEIPT_SUMMARY_LABEL_FONT.setFamily("Arial")

RECEIPT_SUMMARY_TOTAL_FONT=QFont()
RECEIPT_SUMMARY_TOTAL_FONT.setPointSize(11)
RECEIPT_SUMMARY_TOTAL_FONT.setBold(True)
RECEIPT_SUMMARY_TOTAL_FONT.setFamily("Arial")

PAYMENT_SUMMARY_LABEL_FONT=QFont()
PAYMENT_SUMMARY_LABEL_FONT.setPointSize(10)
PAYMENT_SUMMARY_LABEL_FONT.setBold(True)
PAYMENT_SUMMARY_LABEL_FONT.setFamily("Arial")

PAYMENT_SUMMARY_TOTAL_FONT=QFont()
PAYMENT_SUMMARY_TOTAL_FONT.setPointSize(11)
PAYMENT_SUMMARY_TOTAL_FONT.setBold(True)
PAYMENT_SUMMARY_TOTAL_FONT.setFamily("Arial")

CASH_BALANCE_SUMMARY_LABEL_FONT=QFont()
CASH_BALANCE_SUMMARY_LABEL_FONT.setPointSize(11)
CASH_BALANCE_SUMMARY_LABEL_FONT.setBold(True)
CASH_BALANCE_SUMMARY_LABEL_FONT.setFamily("Arial")

CASH_BALANCE_SUMMARY_TOTAL_FONT=QFont()
CASH_BALANCE_SUMMARY_TOTAL_FONT.setPointSize(11)
CASH_BALANCE_SUMMARY_TOTAL_FONT.setBold(True)
CASH_BALANCE_SUMMARY_TOTAL_FONT.setFamily("Arial")

DUMMY_SPACE_FONT=QFont()
DUMMY_SPACE_FONT.setPointSize(8)
